-- MySQL Script generated by MySQL Workbench
-- Thu Sep  7 20:08:22 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`buildings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`buildings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`flats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`flats` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(5) NOT NULL,
  `level` TINYINT(1) NOT NULL,
  `square` FLOAT NOT NULL,
  `building_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_flat2building_idx` (`building_id` ASC) VISIBLE,
  CONSTRAINT `fk_flat2building`
    FOREIGN KEY (`building_id`)
    REFERENCES `mydb`.`buildings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`members` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `names` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`members_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`members_role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role` ENUM('members', 'staff') NULL DEFAULT 'member',
  `member_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rol2member_idx` (`member_id` ASC) VISIBLE,
  CONSTRAINT `fk_rol2member`
    FOREIGN KEY (`member_id`)
    REFERENCES `mydb`.`members` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tenants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tenants` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `names` VARCHAR(120) NOT NULL,
  `auto_allow` TINYINT NULL DEFAULT 0,
  `member_id` INT NULL,
  `flat_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tetant2member_idx` (`member_id` ASC) VISIBLE,
  INDEX `fk_tenant2flat_idx` (`flat_id` ASC) VISIBLE,
  CONSTRAINT `fk_tetant2member`
    FOREIGN KEY (`member_id`)
    REFERENCES `mydb`.`members` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tenant2flat`
    FOREIGN KEY (`flat_id`)
    REFERENCES `mydb`.`flats` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`membrrts_to_flats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`membrrts_to_flats` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `member_id` INT NOT NULL,
  `flat_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_member2flat_idx` (`member_id` ASC) VISIBLE,
  INDEX `fk_flat2member_idx` (`flat_id` ASC) VISIBLE,
  CONSTRAINT `fk_member2flat`
    FOREIGN KEY (`member_id`)
    REFERENCES `mydb`.`members` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_flat2member`
    FOREIGN KEY (`flat_id`)
    REFERENCES `mydb`.`flats` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
